version: '3.1'
services:
    PostgreSQL:
        image: postgres
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=1234
          - POSTGRES_USER=root
          - POSTGRES_DB=postgres
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: 1234
        ports:
          - "5050:80"